name: angular_app
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha+1
  angular_forms: ^2.1.4           
  angular_router: ^2.0.0-alpha+21
  rxdart: ^0.22.6
  http: ^0.12.0+2
  tuple: ^1.0.3
  meta: ^1.1.8
  angular_components: ^0.14.0-alpha+1
  data:
    path: ../module/data
  common:
    path: ../module/common
  movie:
    path: ../module/movie

dev_dependencies:
  angular_test: ^2.4.0
  build_runner: ^1.7.2
  build_test: ^0.10.9+1
  build_web_compilers: ^2.1.0
  test: ^1.9.4
